CREATE TABLE QUIZ (
    idQi INTEGER PRIMARY KEY,
    nomQ TEXT NOT NULL
);

CREATE TABLE QUESTION (
    idQe INTEGER PRIMARY KEY AUTOINCREMENT,
    texte TEXT NOT NULL,
    reponse TEXT NOT NULL,
    idQi INTEGER NOT NULL,
    nbPoints INTEGER DEFAULT 1,
    FOREIGN KEY (idQi) REFERENCES QUIZ(idQi)
);

CREATE TABLE JOUEUR (
    idJ INTEGER PRIMARY KEY AUTOINCREMENT,
    nomJ TEXT NOT NULL
);

CREATE TABLE PARTICIPER (
    idJ INTEGER NOT NULL,
    idQi INTEGER NOT NULL,
    scoreMax INTEGER DEFAULT 0,
    PRIMARY KEY (idJ, idQi),
    FOREIGN KEY (idJ) REFERENCES JOUEUR(idJ),
    FOREIGN KEY (idQi) REFERENCES QUIZ(idQi)
);

CREATE TABLE REPONSE (
    idR INTEGER PRIMARY KEY AUTOINCREMENT,
    idQe INTEGER NOT NULL,
    texte TEXT NOT NULL,
    correct BOOLEAN NOT NULL,
    FOREIGN KEY (idQe) REFERENCES QUESTION(idQe)
);